import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "./nav";
import Hero from "./hero";
import ContentBox from "./contentBox";
import Router from "next/router";

export default function Home() {
  return (
    <div className={styles.app}>
      <Head>
        <title>noahu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Hero/>
        <ContentBox id={'technology'} title={'Technology'} backgroundColor={'red'}/>
        <ContentBox id={'healthcare'} title={'HealthCare'} backgroundColor={'blue'}/>
        <ContentBox id={'biology'} title={'Biology'} backgroundColor={'green'}/>
        <ContentBox id={'hobbies'} title={'Hobbies'} backgroundColor={'purple'}/>
      </div>
      <Nav/>
      <footer className={styles.footer}></footer>
    </div>
  );
}
